### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by puittenbroek** [collective/collective.quickupload#57]
Issue #53 is quite important after the latest csrf hotfix. Could you please make a new release? :)

**Comment by frisi** [comment]
https://pypi.python.org/pypi/collective.quickupload/1.8.1 has has been released

**Comment by mauritsvanrees** [comment]
@frisi Thanks for the release!

BTW, I suggest installing zest.pocompile next to zest.releaser.  This compiles and includes `.mo` files in the release. When checking the difference between your official release and an internal one that I created, I noticed that the official one misses the `.mo` files. No big deal, but I think including them is better. See https://pypi.python.org/pypi/zest.pocompile

**Comment by frisi** [comment]
thanks for the tipp @mauritsvanrees. i installed pocompile and did the 1.8.2. release of quickupload. worked like a charm - .po files are included
